//
// Recipe.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Recipe: Codable {

    public var title: String
    public var href: String
    public var ingredients: String?
    public var thumbnail: String?
    
    public init(title: String , href: String, ingredients: String , thumbnail: String) {
        self.title = title
        self.href = href
        self.ingredients = ingredients
        self.thumbnail = thumbnail
    }

}
